language: ruby
rvm:
    - jruby-9.0.3.0
jdk: oraclejdk8

branches:
    only:
        - master

script:
  - bundle exec rake

bundler_args: "--without development"
cache:
  - bundler

notifications:
  email: false
