language: ruby
rvm:
  - 2.3.0

branches:
    only:
        - master

before_script:
  - sudo apt-get install pdftk

script:
  - bundle exec rake

bundler_args: "--without development"
cache:
  - bundler

notifications:
  email: false
